name: Dependabot Auto-Merge

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Auto-merge Dependabot PRs
        run: |
          if [[ "${{ github.actor }}" == "dependabot[bot]" ]] && \
             ([[ "${{ github.event.label.name }}" == "dependencies" ]] || \
              [[ "${{ github.event.pull_request.labels.*.name }}" =~ "dependencies" ]] || \
              [[ "${{ github.event.pull_request.labels.*.name }}" =~ "security" ]]); then
            echo "Merging pull request from Dependabot..."
            git fetch origin ${{ github.head_ref }}:${{ github.head_ref }}
            git merge --no-commit --no-ff origin/${{ github.head_ref }}
            git commit -m "Merge pull request #${{ github.event.number }} from dependabot[bot]/${{ github.head_ref }}"
            git push origin HEAD:${{ github.head_ref }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Close Pull Request
        if: ${{ success() && github.actor == 'dependabot[bot]' }}
        run: |
              echo "Closing pull request..."
              curl -X PATCH \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github+json" \
                "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}" \
                -d '{"state": "closed"}'
