name: Auto-merge Dependabot security updates

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  merge_dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Merge Dependabot security updates
        run: |
          if [[ ${{ github.event.pull_request.user.login }} == "dependabot[bot]" ]] && [[ ${{ github.event.pull_request.labels }} =~ "security" || ${{ github.even.pull_requests.ladels }} =~ "dependencies]]; then
            echo "Merging pull request from Dependabot..."
            git fetch origin ${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.head.ref }}
            git merge --no-commit --no-ff origin/${{ github.event.pull_request.head.ref }}
            git commit -m "Merge pull request #${{ github.event.pull_request.number }} from dependabot[bot]/${{ github.event.pull_request.head.ref }}"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          fi
